site_name: DataHub
site_description: DataHub is a web service for hosting datapackages.
repo_url: https://github.com/frictionlessdata/dpr-docs
extra_css:
    - css/marmaid.css
    - css/main.css
extra_javascript:
    - js/mermaid.min.js
pages:
- Home: 'index.md'
- Developers:
  - 'Getting started': developers/index.md
  - Deploy: developers/deploy.md
  - API: developers/api.md
  - Authorization: developers/authorization.md
  - Authentication: developers/authentication.md
  - Pusblish: developers/publish.md
- Publishers:
  - 'Getting started': publishers/index.md
  - CLI: publishers/cli.md
theme: readthedocs
markdown_extensions:
  - pymdownx.github
  - fontawesome_markdown
