site_name: Datapackage Registry
site_description: Datapackage Registry is a web service for hosting datapackages.
repo_url: https://github.com/frictionlessdata/dpr-docs
pages:
- Home: 'index.md'
- Developers:
  - 'Getting started': developers/index.md
  - Platform: developers/platform.md
  - Datastore: developers/datastore.md
  - API: developers/api.md
  - CLI: developers/cli.md
  - Authorization: developers/authorization.md
  - Authentication: developers/authentication.md
- Contributors:
  - 'Getting started': contributors/index.md
  - Prepare: contributors/prepare.md
  - Package: contributors/package.md
  - Upload: contributors/upload.md
  - Use: contributors/use.md
- Users:
  - 'Getting started': users/index.md
theme: readthedocs
